version: 2.1

jobs:
  build:
    working_directory: ~/circleci-pipeline
    docker:
      - image: "akshaydocker/circleci-testimage:1.0"
    steps:
      - checkout
      - run: cd ./examples/feed-combiner-java8-webapp/.circleci/ && mvn clean install
  test:
    working_directory: ~/circleci-pipeline
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: cd ./examples/feed-combiner-java8-webapp/.circleci/ &&  mvn test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build